### ISSUE TITLE
运行grad_cam_CNN.py时报错

### ISSUE THREAD

**Issue by YonghuiTAN22** [xwmaxwma/rschange#7]
在运行grad_cam_CNN.py脚本时发生以下报错
Traceback (most recent call last):
  File "F:\deep-learning\change-detection\rschange\tools\grad_cam_CNN.py", line 67, in <module>
    main()
  File "F:\deep-learning\change-detection\rschange\tools\grad_cam_CNN.py", line 44, in main
    grayscale_cam_all = cam(input_tensor=(input[0], input[1]), target_category=target_category)
  File "F:\deep-learning\change-detection\rschange\tools\utilss.py", line 139, in __call__
    o, outputs = self.activations_and_grads(x, y)
ValueError: too many values to unpack (expected 2)
请问代码需要怎么修改呢

**Comment by Casey-bit** [comment]
代码已经完成修改，请参考使用方法再尝试一下，python tools/grad_cam_CNN.py -c configs/cdxformer.py --layer=model.net.decoderhead.LHBlock2.mlp_l，谢谢！
